[workspace]
channels = ["conda-forge"]
name = "georgia-prosecutors"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pixi-pycharm = ">=0.0.8,<0.0.9"
pandas = ">=2.3.1,<3"
fastapi = ">=0.116.1,<0.117"
uvicorn = ">=0.35.0,<0.36"
sqlalchemy = ">=2.0.43,<3"
psycopg2-binary = ">=2.9.10,<3"
alembic = ">=1.16.4,<2"
asyncpg = ">=0.30.0,<0.31"
